name: Deploy Flask App to Azure

on:
  push:
    branches:
      - main  # Deploy when code is pushed to the main branch

permissions:  
  id-token: write  # 🔹 This grants permission for OIDC authentication  
  contents: read  # 🔹 Allows reading repo contents  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Zip the application
        run: zip -r app.zip . -x "env/*" ".git/*"

      - name: Azure Login with OIDC  # 🔹 Use GitHub OIDC for authentication
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          allow-no-subscriptions: true

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: "flask-energy-app"
          package: app.zip
